<?php

use App\Models\DeveloperUsage\Menu\BackendSystemMenu;
use Illuminate\Database\Seeder;

/**
 * Class BackendSystemMenuSeeder
 */
class BackendSystemMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        BackendSystemMenu::insert(
            [
                [
                    'id' => '1',
                    'label' => '运营管理',
                    'en_name' => 'operasyon',
                    'route' => '/operasyon',
                    'pid' => 0,
                    'icon' => 'anticon anticon-appstore',
                    'display' => 1,
                    'level' => 1,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '2',
                    'label' => '域名管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 1,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '3',
                    'label' => '系统设置',
                    'en_name' => 'operasyon.setting',
                    'route' => '/operasyon/operasyon-setting',
                    'pid' => 1,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '5',
                    'label' => '活动列表',
                    'en_name' => 'activity.list',
                    'route' => '/operasyon/activity-list',
                    'pid' => 64,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '9',
                    'label' => '消息管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 64,
                    'icon' => null,
                    'display' => 0,
                    'level' => 3,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '11',
                    'label' => '管理员角色',
                    'en_name' => 'manager.character',
                    'route' => '/operasyon/manager-character',
                    'pid' => 1,
                    'icon' => 'null',
                    'display' => 1,
                    'level' => 2,
                    'sort' => 3,
                    'type' => 1,
                ],
                [
                    'id' => '12',
                    'label' => '游戏管理',
                    'en_name' => 'game',
                    'route' => '/game',
                    'pid' => 0,
                    'icon' => 'anticon anticon-rocket',
                    'display' => 1,
                    'level' => 1,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '13',
                    'label' => '彩种信息',
                    'en_name' => 'game.type',
                    'route' => '/game/game-type',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '14',
                    'label' => '系列玩法',
                    'en_name' => 'game.play',
                    'route' => '/game/game-play',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '15',
                    'label' => '玩法组管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 3,
                    'type' => 1,
                ],
                [
                    'id' => '16',
                    'label' => '投注方式与玩法关系',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '17',
                    'label' => '奖期',
                    'en_name' => 'lottery.issue',
                    'route' => '/game/lottery-issue',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 5,
                    'type' => 1,
                ],
                [
                    'id' => '18',
                    'label' => '系列',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 6,
                    'type' => 1,
                ],
                [
                    'id' => '19',
                    'label' => '注单',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 7,
                    'type' => 1,
                ],
                [
                    'id' => '20',
                    'label' => '追号',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 8,
                    'type' => 1,
                ],
                [
                    'id' => '21',
                    'label' => '开奖',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 9,
                    'type' => 1,
                ],
                [
                    'id' => '22',
                    'label' => '抓取记录',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 10,
                    'type' => 1,
                ],
                [
                    'id' => '23',
                    'label' => '推送记录',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 11,
                    'type' => 1,
                ],
                [
                    'id' => '24',
                    'label' => '告警记录',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 12,
                    'type' => 1,
                ],
                [
                    'id' => '25',
                    'label' => '玩家管理',
                    'en_name' => 'manage',
                    'route' => '/manage',
                    'pid' => 0,
                    'icon' => 'anticon anticon-user',
                    'display' => 1,
                    'level' => 1,
                    'sort' => 3,
                    'type' => 1,
                ],
                [
                    'id' => '26',
                    'label' => '用户绑定动作',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '27',
                    'label' => '管理用户',
                    'en_name' => 'manage.user',
                    'route' => '/manage/manage-user',
                    'pid' => 25,
                    'icon' => 'null',
                    'display' => 1,
                    'level' => 2,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '28',
                    'label' => '创建总代',
                    'en_name' => 'create.general.agent',
                    'route' => '/manage/create-general-agent',
                    'pid' => 25,
                    'icon' => 'null',
                    'display' => 1,
                    'level' => 2,
                    'sort' => 3,
                    'type' => 1,
                ],
                [
                    'id' => '29',
                    'label' => '密码审核',
                    'en_name' => 'passport.check',
                    'route' => '/manage/passport-check',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '30',
                    'label' => '资金密码审核',
                    'en_name' => 'capital.passport.check',
                    'route' => '/manage/capital-passport-check',
                    'pid' => 25,
                    'icon' => 'null',
                    'display' => 1,
                    'level' => 2,
                    'sort' => 5,
                    'type' => 1,
                ],
                [
                    'id' => '32',
                    'label' => '开户链接管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 6,
                    'type' => 1,
                ],
                [
                    'id' => '33',
                    'label' => '代理奖金组管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 7,
                    'type' => 1,
                ],
                [
                    'id' => '34',
                    'label' => '卡号反查',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 8,
                    'type' => 1,
                ],
                [
                    'id' => '35',
                    'label' => '代理盈亏报表',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 9,
                    'type' => 1,
                ],
                [
                    'id' => '36',
                    'label' => '绑定银行卡',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 10,
                    'type' => 1,
                ],
                [
                    'id' => '38',
                    'label' => '转移下级用户列表',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 11,
                    'type' => 1,
                ],
                [
                    'id' => '40',
                    'label' => '银行卡',
                    'en_name' => 'bank.check',
                    'route' => '/manage/manage-bank',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 12,
                    'type' => 1,
                ],
                [
                    'id' => '41',
                    'label' => '分红契约',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 13,
                    'type' => 1,
                ],
                [
                    'id' => '42',
                    'label' => '工资契约',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 14,
                    'type' => 1,
                ],
                [
                    'id' => '43',
                    'label' => '账户管理',
                    'en_name' => 'account',
                    'route' => '/account',
                    'pid' => 0,
                    'icon' => 'anticon anticon-profile',
                    'display' => 0,
                    'level' => 1,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '44',
                    'label' => '玩家账户',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 43,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '45',
                    'label' => '账变记录',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 43,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '47',
                    'label' => '报表管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'icon' => 'anticon anticon-profile',
                    'display' => 1,
                    'level' => 1,
                    'sort' => 5,
                    'type' => 1,
                ],
                [
                    'id' => '48',
                    'label' => '充值报表',
                    'en_name' => 'recharge.report',
                    'route' => '/report/recharge-report',
                    'pid' => 81,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '49',
                    'label' => '账变报表',
                    'en_name' => 'account.report',
                    'route' => '/report/account-report',
                    'pid' => 81,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '59',
                    'label' => '操作日志',
                    'en_name' => 'operation.log',
                    'route' => '/operasyon/operation-log',
                    'pid' => 1,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '60',
                    'label' => '账号冻结设置按钮',
                    'en_name' => 'isbtn',
                    'route' => '/manage/permission-setting',
                    'pid' => 27,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '61',
                    'label' => '省市地区列表',
                    'en_name' => 'city.list',
                    'route' => '/manage/city-list',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 15,
                    'type' => 1,
                ],
                [
                    'id' => '64',
                    'label' => '活动管理',
                    'en_name' => 'activity',
                    'route' => '/operasyon/activity',
                    'pid' => 1,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 5,
                    'type' => 1,
                ],
                [
                    'id' => '65',
                    'label' => '分类管理',
                    'en_name' => 'category.manage',
                    'route' => '/operasyon/category-manage',
                    'pid' => 64,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 3,
                    'type' => 1,
                ],
                [
                    'id' => '66',
                    'label' => '文章管理',
                    'en_name' => 'article.manage',
                    'route' => '/operasyon/article-manage',
                    'pid' => 64,
                    'icon' => null,
                    'display' => 0,
                    'level' => 3,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '69',
                    'label' => '银行管理',
                    'en_name' => 'bank.manage',
                    'route' => '/operasyon/bank-manage',
                    'pid' => 73,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '70',
                    'label' => '额度管理',
                    'en_name' => 'quota.manage',
                    'route' => '/operasyon/quota-manage',
                    'pid' => 73,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '73',
                    'label' => '资金操作',
                    'en_name' => 'prize.operate',
                    'route' => '/manage/prize-handle',
                    'pid' => 1,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 6,
                    'type' => 1,
                ],
                [
                    'id' => '79',
                    'label' => '资金管理',
                    'en_name' => 'prize.manage',
                    'route' => '/manage/prize-manage',
                    'pid' => 25,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 16,
                    'type' => 1,
                ],
                [
                    'id' => '80',
                    'label' => '人工充值',
                    'en_name' => 'recharge',
                    'route' => '/manage/recharge',
                    'pid' => 79,
                    'icon' => null,
                    'display' => 0,
                    'level' => 3,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '81',
                    'label' => '开发管理',
                    'en_name' => 'developer.handler',
                    'route' => '#',
                    'pid' => 0,
                    'icon' => 'anticon anticon-link',
                    'display' => 1,
                    'level' => 1,
                    'sort' => 6,
                    'type' => 1,
                ],
                [
                    'id' => '82',
                    'label' => '商户端菜单管理',
                    'en_name' => 'developer.menu',
                    'route' => '/developer/add-menu',
                    'pid' => 81,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '97',
                    'label' => '充值审核',
                    'en_name' => 'recharge.check',
                    'route' => '/manage/recharge-check',
                    'pid' => 79,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '98',
                    'label' => '拖拽',
                    'en_name' => 'drag',
                    'route' => '/developer/drag',
                    'pid' => 81,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '99',
                    'label' => '账变类型',
                    'en_name' => 'account.type',
                    'route' => '/manage/account-type',
                    'pid' => 79,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 3,
                    'type' => 1,
                ],
                [
                    'id' => '100',
                    'label' => '路由管理',
                    'en_name' => 'route.manage',
                    'route' => '/developer/route-manage',
                    'pid' => 81,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 3,
                    'type' => 1,
                ],
                [
                    'id' => '101',
                    'label' => '广告',
                    'en_name' => 'ad.manage',
                    'route' => 'ad-manage',
                    'pid' => 0,
                    'icon' => 'anticon anticon-bulb',
                    'display' => 1,
                    'level' => 1,
                    'sort' => 7,
                    'type' => 1,
                ],
                [
                    'id' => '102',
                    'label' => '广告类型',
                    'en_name' => 'ad.type',
                    'route' => '/ad-manage/ad-type',
                    'pid' => 101,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '103',
                    'label' => '主页管理',
                    'en_name' => 'page.manage',
                    'route' => '/operasyon/page-manage',
                    'pid' => 1,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 7,
                    'type' => 1,
                ],
                [
                    'id' => '104',
                    'label' => '图标',
                    'en_name' => 'logo',
                    'route' => '/operasyon/app-logo',
                    'pid' => 103,
                    'icon' => null,
                    'display' => 0,
                    'level' => 3,
                    'sort' => 1,
                    'type' => 1,
                ],
                [
                    'id' => '105',
                    'label' => '一级导航',
                    'en_name' => 'nav.one',
                    'route' => '/operasyon/nav-one',
                    'pid' => 103,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '106',
                    'label' => '二级导航',
                    'en_name' => 'nave.two',
                    'route' => '/operasyon/nav-two',
                    'pid' => 103,
                    'icon' => null,
                    'display' => 0,
                    'level' => 3,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '107',
                    'label' => '轮播图',
                    'en_name' => 'bannar',
                    'route' => '/operasyon/bannar',
                    'pid' => 103,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '108',
                    'label' => '主题板块',
                    'en_name' => 'page.model',
                    'route' => '/operasyon/page-model',
                    'pid' => 103,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 5,
                    'type' => 1,
                ],
                [
                    'id' => '109',
                    'label' => '页脚一',
                    'en_name' => 'foot.one',
                    'route' => '/operasyon/foot-one',
                    'pid' => 103,
                    'icon' => null,
                    'display' => 0,
                    'level' => 3,
                    'sort' => 6,
                    'type' => 1,
                ],
                [
                    'id' => '110',
                    'label' => '页脚2',
                    'en_name' => 'foot.two',
                    'route' => '/operasyon/foot-two',
                    'pid' => 103,
                    'icon' => null,
                    'display' => 0,
                    'level' => 3,
                    'sort' => 6,
                    'type' => 1,
                ],
                [
                    'id' => '111',
                    'label' => '投注端菜单管理',
                    'en_name' => 'betting.menu',
                    'route' => '/developer/betting-menu',
                    'pid' => 81,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '112',
                    'label' => '公告管理',
                    'en_name' => 'announcement.manage',
                    'route' => '/operasyon/announcement-manage',
                    'pid' => 1,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 8,
                    'type' => 1,
                ],
                [
                    'id' => '113',
                    'label' => '玩法等级管理',
                    'en_name' => 'play.level',
                    'route' => '/developer/play-level',
                    'pid' => 81,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 5,
                    'type' => 1,
                ],
                [
                    'id' => '114',
                    'label' => '前台操作日志',
                    'en_name' => 'frontend.data.list',
                    'route' => '/operasyon/frontend-list',
                    'pid' => 1,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 9,
                    'type' => 1,
                ],
                [
                    'id' => '115',
                    'label' => '注单报表',
                    'en_name' => 'user.bets',
                    'route' => '/report/user-bets',
                    'pid' => 47,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 3,
                    'type' => 1,
                ],
                [
                    'id' => '117',
                    'label' => '帮助中心',
                    'en_name' => 'helper',
                    'route' => '/operasyon/helper',
                    'pid' => 103,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 8,
                    'type' => 1,
                ],
                [
                    'id' => '118',
                    'label' => '任务调度',
                    'en_name' => 'task.scheduling',
                    'route' => '/developer/task-scheduling',
                    'pid' => 81,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 6,
                    'type' => 1,
                ],
                [
                    'id' => '119',
                    'label' => '彩种系列',
                    'en_name' => 'lottery.series',
                    'route' => '/game/lottery-series',
                    'pid' => 12,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 13,
                    'type' => 1,
                ],
                [
                    'id' => '121',
                    'label' => '提现列表',
                    'en_name' => 'withdraw.list',
                    'route' => '/manage/withdraw-list',
                    'pid' => 79,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '122',
                    'label' => '充值按钮',
                    'en_name' => 'isbtn',
                    'route' => '/manage/recharge',
                    'pid' => 27,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 2,
                    'type' => 1,
                ],
                [
                    'id' => '123',
                    'label' => '扣减按钮',
                    'en_name' => 'isbtn',
                    'route' => '/manage/reduce',
                    'pid' => 27,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 3,
                    'type' => 1,
                ],
                [
                    'id' => '124',
                    'label' => '重置登录密码按钮',
                    'en_name' => 'isbtn',
                    'route' => '/manage/reset-password',
                    'pid' => 27,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '125',
                    'label' => '重置资金密码按钮',
                    'en_name' => 'isbtn',
                    'route' => '/manage/reset-fund-password',
                    'pid' => 27,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 5,
                    'type' => 1,
                ],
                [
                    'id' => '126',
                    'label' => '权限操作历史按钮',
                    'en_name' => 'isbtn',
                    'route' => '/manage/history',
                    'pid' => 27,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 6,
                    'type' => 1,
                ],
                [
                    'id' => '127',
                    'label' => '账变记录查询按钮',
                    'en_name' => 'isbtn',
                    'route' => '/manage/account-change',
                    'pid' => 27,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 7,
                    'type' => 1,
                ],
                [
                    'id' => '128',
                    'label' => '充值记录按钮',
                    'en_name' => 'isbtn',
                    'route' => '/manage/recharge-list',
                    'pid' => 27,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 8,
                    'type' => 1,
                ],
                [
                    'id' => '129',
                    'label' => '查看直属按钮',
                    'en_name' => 'isbtn',
                    'route' => '/manage/check-parent',
                    'pid' => 27,
                    'icon' => null,
                    'display' => 1,
                    'level' => 3,
                    'sort' => 9,
                    'type' => 1,
                ],
                [
                    'id' => '130',
                    'label' => '提现报表',
                    'en_name' => 'withdraw.report',
                    'route' => '/report/withdraw-report',
                    'pid' => 47,
                    'icon' => null,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 4,
                    'type' => 1,
                ],
                [
                    'id' => '131',
                    'label' => '三方路由管理',
                    'en_name' => 'thirdparty.route',
                    'route' => 'thirdparty/route',
                    'pid' => 81,
                    'icon' => null,
                    'display' => 0,
                    'level' => 2,
                    'sort' => 7,
                    'type' => 1,
                ],
                [
                    'id' => '132',
                    'label' => '提现详情',
                    'en_name' => 'withdraw.detail',
                    'route' => '/withdraw/detail',
                    'pid' => 79,
                    'icon' => null,
                    'display' => 0,
                    'level' => 3,
                    'sort' => 5,
                    'type' => 1,
                ],
                [
                    'id' => '136',
                    'label' => '测试',
                    'en_name' => 'test',
                    'route' => '/test/test',
                    'pid' => 0,
                    'icon' => null,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 50,
                    'type' => 1,
                ],
                [
                    'id' => '137',
                    'label' => '测试1',
                    'en_name' => 'bbb.bb',
                    'route' => '#',
                    'pid' => 0,
                    'icon' => null,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 50,
                    'type' => 1,
                ],
                [
                    'id' => '138',
                    'label' => '菜单管理2',
                    'en_name' => 'testq',
                    'route' => '/test/test',
                    'pid' => 0,
                    'icon' => null,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 50,
                    'type' => 1,
                ],
                [
                    'id' => '140',
                    'label' => '新父级菜单',
                    'en_name' => 'bbb.bbbb',
                    'route' => '#',
                    'pid' => 0,
                    'icon' => null,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 50,
                    'type' => 1,
                ],
            ],
        );
    }
}
