<?php

use App\Models\Platform\GamePlatform;
use Illuminate\Database\Seeder;

/**
 * Class GamePlatformSeeder
 */
class GamePlatformSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        GamePlatform::insert(
            [
             [
              'platform_id'  => 1,
              'game_id'      => 1,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 2,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 3,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 4,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 5,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 6,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 7,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 8,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 9,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 10,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 11,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 12,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 13,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 14,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 15,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 16,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 17,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 18,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 19,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 20,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 21,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 22,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 23,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 24,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 25,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 26,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 27,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 28,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 29,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 30,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 31,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 32,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 33,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 34,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 35,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 36,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 37,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 38,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 39,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 40,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 41,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 42,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 43,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 44,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
             [
              'platform_id'  => 1,
              'game_id'      => 45,
              'status'       => 1,
              'hot_new'      => 0,
              'device'       => 3,
              'is_recommend' => 0,
             ],
            ],
        );
    }
}
