<?php

use App\Models\Game\GameTypePlatform;
use Illuminate\Database\Seeder;

/**
 * Class GameTypePlatformSeeder
 */
class GameTypePlatformSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        GameTypePlatform::insert(
            [
                [
                    'platform_id' => 1,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 2,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 3,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 4,
                    'device' => 0,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 5,
                    'device' => 3,
                    'status' => 0,
                ],
                [
                    'platform_id' => 1,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 1,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 5,
                    'device' => 3,
                    'status' => 0,
                ],
                [
                    'platform_id' => 2,
                    'type_id' => 5,
                    'device' => 1,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 5,
                    'device' => 3,
                    'status' => 0,
                ],
                [
                    'platform_id' => 12,
                    'type_id' => 5,
                    'device' => 1,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 5,
                    'device' => 3,
                    'status' => 0,
                ],
                [
                    'platform_id' => 13,
                    'type_id' => 5,
                    'device' => 1,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 5,
                    'device' => 3,
                    'status' => 0,
                ],
                [
                    'platform_id' => 14,
                    'type_id' => 5,
                    'device' => 1,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 5,
                    'device' => 3,
                    'status' => 0,
                ],
                [
                    'platform_id' => 15,
                    'type_id' => 5,
                    'device' => 1,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 5,
                    'device' => 3,
                    'status' => 0,
                ],
                [
                    'platform_id' => 16,
                    'type_id' => 5,
                    'device' => 1,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 5,
                    'device' => 3,
                    'status' => 0,
                ],
                [
                    'platform_id' => 17,
                    'type_id' => 5,
                    'device' => 1,
                    'status' => 0,
                ],
                [
                    'platform_id' => 18,
                    'type_id' => 5,
                    'device' => 2,
                    'status' => 0,
                ],
                [
                    'platform_id' => 18,
                    'type_id' => 5,
                    'device' => 3,
                    'status' => 0,
                ],
                [
                    'platform_id' => 18,
                    'type_id' => 5,
                    'device' => 1,
                    'status' => 0,
                ],
            ],
        );
    }
}
