<?php

use App\Models\Admin\MerchantAdminUser;
use Illuminate\Database\Seeder;

/**
 * Class MerchantAdminUserSeeder
 */
class MerchantAdminUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        MerchantAdminUser::insert(
            [
              [
              'id' => '1',
              'name' => 'ling',
              'email' => 'ling@gmail.com',
              'password' => '$2y$10$MKKGeBpoDfzfcewJ4Mrk.uTCIcSSvowXwPeKw0LNwY8K60pz7QL3G',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '1',
              'status' => '1',
              'platform_sign' => 'b',
              'chargeable_fund' => '100',

              ],
              [
              'id' => '11',
              'name' => 'ling001',
              'email' => 'ling001@gmail.com',
              'password' => '$2y$10$bxBpMKcvC1.JSfWntulHlOwIgBXNKCE3ftTR0I0AcBZyB8SnHam3S',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '34',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '15',
              'name' => 'ling005',
              'email' => 'ling005@gmail.com',
              'password' => '$2y$10$bP0DE5of9NGGccOQm61.7uYxPq4faTvFw42fh9KdcVqchoxj4SMnC',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '36',
              'status' => '1',
              'platform_sign' => 'b',
              'chargeable_fund' => '',
              ],
              [
              'id' => '16',
              'name' => 'ling006',
              'email' => 'ling006@gmail.com',
              'password' => '$2y$10$2fG5EPEMp2gVmZ7GSx5iRuO7jduZPDO0uzrXp0VKtQPiu8ZUk4fb2',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '36',
              'status' => '1',
              'platform_sign' => 'b',
              'chargeable_fund' => '',
              ],
              [
              'id' => '17',
              'name' => 'ling007',
              'email' => 'ling007@gmail.com',
              'password' => '$2y$10$Kl/gL/MolTGTL1JemKfwYeB9NkF3DsApu.eIFTyCB8vyvp9qpC3tm',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '36',
              'status' => '1',
              'platform_sign' => 'b',
              'chargeable_fund' => '',
              ],
              [
              'id' => '19',
              'name' => 'ling008',
              'email' => 'ling008@gmail.com',
              'password' => '$2y$10$xUmo2N3VbhJfk8BZIQSF6O49J.w7Jh0w01Hg0CDSYRa3mihxxkeNm',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '36',
              'status' => '1',
              'platform_sign' => 'b',
              'chargeable_fund' => '',
              ],
              [
              'id' => '21',
              'name' => 'ling0011',
              'email' => 'ling0011@gmail.com',
              'password' => '$2y$10$kSPOJMpdufOJYN/gfMguMuburVw8hRjRfFsnhumnvaCcTvEtCINqa',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '39',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '22',
              'name' => 'ling002',
              'email' => 'ling002@gmail.com',
              'password' => '$2y$10$L40erHCRzKo0GBMckU1MDeSfgda5uBYSvqkkm1bWShbzIQdySkgbe',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '40',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '23',
              'name' => 'ling003',
              'email' => 'ling003@gmail.com',
              'password' => '$2y$10$u3/L4PoeHuByi2nkHNCHqegn/cy9nvC5jWo0CMRnnBYWWLfPD.lFC',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '41',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '24',
              'name' => 'ling004',
              'email' => 'ling004@gmail.com',
              'password' => '$2y$10$WE3ZGwm9HHDZa22Z54JDdenIMQ1bxlR72KlYRST.G9RMxYIaQvUFe',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '42',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '25',
              'name' => 'ling0010',
              'email' => 'ling0010@gmail.com',
              'password' => '$2y$10$4ybk1jaRetWOdoLjE5EN8ua9oQhqURhyzTYDJe9tKUdTYFST2a5ce',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '43',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '26',
              'name' => 'ling012',
              'email' => 'ling012@gmail.com',
              'password' => '$2y$10$Rq6iLS1lDVcLEP6GrUoo6O8JlF02Ff.DFvyu9heYuaxS6AR9x0zcO',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '37',
              'status' => '1',
              'platform_sign' => 'b',
              'chargeable_fund' => '',
              ],
              [
              'id' => '27',
              'name' => 'ling016',
              'email' => 'ling016@gmail.com',
              'password' => '$2y$10$e9EMe30G1FU5dXsXNJlBp.OW4/Ro3ugFZgHSUcfWwL09oTSjdpdc6',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '45',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '28',
              'name' => 'ling017',
              'email' => 'ling017@gmail.com',
              'password' => '$2y$10$VXa.8NSMF1yeD74Qh7lCquzYbAqnGz7OpTEGCPGYIcFc36g8DfWb6',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '46',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '29',
              'name' => 'ling018',
              'email' => 'ling018@gmail.com',
              'password' => '$2y$10$GSwGvHkwgQDy9KIpWZzmQ.Mbwh/ps70M9blsC.zUIVK24HQoEfTKW',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '47',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '30',
              'name' => 'ling019',
              'email' => 'ling019@gmail.com',
              'password' => '$2y$10$FeUiD3c/XSj6yePhvEo/L.qYG6ei3lKxgnJhten2ptg.PM1wvZPOe',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '48',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '31',
              'name' => 'ling020',
              'email' => 'ling020@gmail.com',
              'password' => '$2y$10$CygR4C40XV//iSF8D89qv..hhPTiAP.CgJYV6X5G0SWejBMiYqAq2',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '49',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '32',
              'name' => 'ling021',
              'email' => 'ling021@gmail.com',
              'password' => '$2y$10$DHdo.8/HBLPHNkGGy76nW.1PQFUcLZHXK/0EYvNXE9DVDvxscB6I.',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '50',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '33',
              'name' => 'ling022',
              'email' => 'ling022@gmail.com',
              'password' => '$2y$10$GWbNyJcEaoq.uiifn8YZIuDfJ4jpU0ouf8E8G3b9f9NpCjOTByy8u',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '51',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '34',
              'name' => 'ling023',
              'email' => 'ling023@gmail.com',
              'password' => '$2y$10$T9P4UtLngnfXNE7j0hXoT.0UAcz6.9kcoVYm0B/ZSvyvqLDy8o9ry',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '52',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '35',
              'name' => 'ling025',
              'email' => 'ling025@gmail.com',
              'password' => '$2y$10$7AI0i8kl/3J5uAjcuYkGTOHSj5O/0Zr3oD502T8q6r5rShqS8a7Z.',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '53',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
              [
              'id' => '36',
              'name' => 'ling028',
              'email' => 'ling028@gmail.com',
              'password' => '$2y$10$5VLb067q/cxXYTUEFC2PwOasSh/AwfQOx6pD2UCbB7LbQO0XsmTLy',
              'remember_token' => '',
              'is_test' => '0',
              'group_id' => '54',
              'status' => '1',
              'platform_sign' => '',
              'chargeable_fund' => '',
              ],
            ],
        );
    }
}
