<?php

use App\Models\DeveloperUsage\Menu\MerchantSystemMenu;
use Illuminate\Database\Seeder;

/**
 * Class MerchantSystemMenuSeeder
 */
class MerchantSystemMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        MerchantSystemMenu::insert(
            [
             [
              'id'      => 1,
              'label'   => '首页',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 2,
              'label'   => '首页',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 1,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 3,
              'label'   => '会员管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 4,
              'label'   => '会员列表',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 3,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 5,
              'label'   => '登录记录',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 3,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 6,
              'label'   => '标签管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 3,
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 7,
              'label'   => '黑名单管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 3,
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 8,
              'label'   => '等级设置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 3,
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 9,
              'label'   => '洗码设置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 3,
              'display' => 1,
              'level'   => 2,
              'sort'    => 6,
              'type'    => 1,
             ],
             [
              'id'      => 10,
              'label'   => '财务管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 11,
              'label'   => '入款订单',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 10,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 12,
              'label'   => '人工存取',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 10,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 13,
              'label'   => '出款审核',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 10,
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 14,
              'label'   => '出款订单',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 10,
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 15,
              'label'   => '资金帐变',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 10,
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 16,
              'label'   => '公告管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 17,
              'label'   => '跑马灯消息',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 16,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 18,
              'label'   => '系统公告',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 16,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 19,
              'label'   => '登录弹窗公告',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 16,
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 20,
              'label'   => '轮播公告',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 16,
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 21,
              'label'   => '邮件系统',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 22,
              'label'   => '发邮件',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 21,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 23,
              'label'   => '收件箱',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 21,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 24,
              'label'   => '已发邮件',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 21,
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 25,
              'label'   => '短信推送',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 21,
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 26,
              'label'   => '报表管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 6,
              'type'    => 1,
             ],
             [
              'id'      => 27,
              'label'   => '个人报表',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 26,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 28,
              'label'   => '游戏报表',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 26,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 29,
              'label'   => '公司报表',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 26,
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 30,
              'label'   => '会员稽查',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 26,
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 31,
              'label'   => '平台注单',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 26,
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 32,
              'label'   => '活动报表',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 26,
              'display' => 1,
              'level'   => 2,
              'sort'    => 6,
              'type'    => 1,
             ],
             [
              'id'      => 33,
              'label'   => '会员洗码',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 26,
              'display' => 1,
              'level'   => 2,
              'sort'    => 7,
              'type'    => 1,
             ],
             [
              'id'      => 34,
              'label'   => '游戏管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 7,
              'type'    => 1,
             ],
             [
              'id'      => 35,
              'label'   => 'H5游戏管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 34,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 36,
              'label'   => 'PC游戏管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 34,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 37,
              'label'   => 'APP游戏管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 34,
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 38,
              'label'   => '平台管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 34,
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 39,
              'label'   => '分类管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 34,
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 40,
              'label'   => '活动管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 8,
              'type'    => 1,
             ],
             [
              'id'      => 41,
              'label'   => '静态活动',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 40,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 42,
              'label'   => '动态活动',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 40,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 43,
              'label'   => '金流管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 9,
              'type'    => 1,
             ],
             [
              'id'      => 44,
              'label'   => '线下支付配置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 43,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 45,
              'label'   => '线上金流配置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 43,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 46,
              'label'   => '出款银行管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 43,
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 47,
              'label'   => '推广配置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 10,
              'type'    => 1,
             ],
             [
              'id'      => 48,
              'label'   => '推广配置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 47,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 49,
              'label'   => '推广图片配置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 47,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 50,
              'label'   => '设置管理',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 1,
              'level'   => 1,
              'sort'    => 11,
              'type'    => 1,
             ],
             [
              'id'      => 51,
              'label'   => '管理员分组',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 50,
              'display' => 1,
              'level'   => 2,
              'sort'    => 1,
              'type'    => 1,
             ],
             [
              'id'      => 52,
              'label'   => '全域设置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 50,
              'display' => 1,
              'level'   => 2,
              'sort'    => 2,
              'type'    => 1,
             ],
             [
              'id'      => 53,
              'label'   => '客服设置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 50,
              'display' => 1,
              'level'   => 2,
              'sort'    => 3,
              'type'    => 1,
             ],
             [
              'id'      => 54,
              'label'   => '帮助设置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 50,
              'display' => 1,
              'level'   => 2,
              'sort'    => 4,
              'type'    => 1,
             ],
             [
              'id'      => 55,
              'label'   => '操作记录',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 50,
              'display' => 1,
              'level'   => 2,
              'sort'    => 5,
              'type'    => 1,
             ],
             [
              'id'      => 56,
              'label'   => '银行卡反查中心',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 50,
              'display' => 1,
              'level'   => 2,
              'sort'    => 6,
              'type'    => 1,
             ],
             [
              'id'      => 57,
              'label'   => '系统设置',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 0,
              'display' => 0,
              'level'   => 1,
              'sort'    => 12,
              'type'    => 1,
             ],
             [
              'id'      => 58,
              'label'   => '全域',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 57,
              'display' => 0,
              'level'   => 1,
              'sort'    => 12,
              'type'    => 1,
             ],
             [
              'id'      => 59,
              'label'   => '游戏回调',
              'en_name' => '',
              'route'   => '#',
              'pid'     => 57,
              'display' => 0,
              'level'   => 1,
              'sort'    => 12,
              'type'    => 1,
             ],
            ],
        );
    }
}
