<?php

use App\Models\DeveloperUsage\Menu\MerchantSystemMenu;
use Illuminate\Database\Seeder;

/**
 * Class MerchantSystemMenuSeeder
 */
class MerchantSystemMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        MerchantSystemMenu::insert(
            [
                [
                    'label' => '首页',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '首页',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 1,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '会员管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '会员列表',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 3,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '登录记录',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 3,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '标签管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 3,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '黑名单管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 3,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '等级设置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 3,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '洗码设置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 3,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '财务管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '入款订单',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 10,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '人工存取',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 10,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '出款审核',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 10,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '出款订单',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 10,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '资金帐变',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 10,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '公告管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '跑马灯消息',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 16,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '系统公告',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 16,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '登录弹窗公告',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 16,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '轮播公告',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 16,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '邮件系统',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '发邮件',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 21,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '收件箱',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 21,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '已发邮件',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 21,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '短信推送',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 21,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '报表管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '个人报表',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 26,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '游戏报表',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 26,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '公司报表',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 26,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '会员稽查',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 26,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '平台注单',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 26,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '活动报表',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 26,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '会员洗码',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 26,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '游戏管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => 'H5游戏管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 34,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => 'PC游戏管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 34,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => 'APP游戏管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 34,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '平台管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 34,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '分类管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 34,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '活动管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '静态活动',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 40,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '动态活动',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 40,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '金流管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '线下支付配置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 43,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '线上金流配置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 43,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '出款银行管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 43,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '推广配置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '推广配置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 47,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '推广图片配置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 47,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '设置管理',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 1,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '管理员分组',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 50,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '全域设置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 50,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '客服设置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 50,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '帮助设置',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 50,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '操作记录',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 50,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '银行卡反查中心',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 50,
                    'display' => 1,
                    'level' => 2,
                    'sort' => 0,
                    'type' => 1,
                ],
                [
                    'label' => '全域',
                    'en_name' => '',
                    'route' => '#',
                    'pid' => 0,
                    'display' => 0,
                    'level' => 1,
                    'sort' => 0,
                    'type' => 1,
                ],
            ],
        );
    }
}
