<?php

use App\Models\DeveloperUsage\Backend\SystemRoutesBackend;
use Illuminate\Database\Seeder;

/**
 * Class SystemRoutesBackendSeeder
 */
class SystemRoutesBackendSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        SystemRoutesBackend::insert(
            [
                [
                    'route_name' => 'headquarters-api.login',
                    'method' => 'login',
                    'menu_group_id' => 5,
                    'is_open' => 1,
                ],
                [
                    'route_name' => 'headquarters-api.menu.get-all-menu',
                    'method' => 'getAllMenu',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.menu.current-admin-menu',
                    'method' => 'currentPartnerMenu',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.menu.all-require-infos',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.menu.add',
                    'method' => 'add',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.menu.delete',
                    'method' => 'delete',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.menu.edit',
                    'method' => 'edit',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.menu.change-parent',
                    'method' => 'changeParent',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-type.add-do',
                    'method' => 'addDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.backend-admin-group.detail',
                    'method' => 'detail',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-type.edit-do',
                    'method' => 'editDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-type.index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-type.del-do',
                    'method' => 'delDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.backend-admin-group.create',
                    'method' => 'create',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.backend-admin-group.edit',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.backend-admin-group.delete-access-group',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.backend-admin-group.specific-group-users',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-vendor.add-do',
                    'method' => 'addDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-vendor.edit-do',
                    'method' => 'editDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-vendor.index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-vendor.del-do',
                    'method' => 'delDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.logout',
                    'method' => 'logout',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.merchant-admin-user.do-add',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.logout',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game.add-do',
                    'method' => 'addDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game.edit-do',
                    'method' => 'editDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game.index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game.del-do',
                    'method' => 'delDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.menu.current-admin-menu',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.headquarters-admin.get-all-users',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-group.create',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-group.detail',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-group.edit',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-group.delete',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-group.specific-group-users',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-group.delete',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.menu.current-admin-menu',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.menu.current-admin-menu',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-type.add-do',
                    'method' => 'addDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-type.edit-do',
                    'method' => 'editDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-type.index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-type.del-do',
                    'method' => 'delDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-vendor.add-do',
                    'method' => 'addDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-vendor.edit-do',
                    'method' => 'editDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-vendor.index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-vendor.del-do',
                    'method' => 'delDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-user.create',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-user.get-all-admins',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-user.update-admin-group',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-user.delete-user',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-user.reset-password',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-user.self-reset-password',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.merchant-admin-user.search-admin',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-channel.add-do',
                    'method' => 'addDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-channel.edit-do',
                    'method' => 'editDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-channel.index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-channel.del-do',
                    'method' => 'delDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.merchant-menu.get-all-menu',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.merchant-menu.get-all-menu',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.merchant-menu.add',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.merchant-menu.edit',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.merchant-menu.delete',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game.get-search-condition',
                    'method' => 'getSearchCondition',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.merchant-menu.change-parent',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-channel.get-search-condition',
                    'method' => 'getSearchCondition',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-channel.status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-vendor.status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-type.status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game.status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-type.status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-vendor.opt-status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-vendor.opt-index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-type.opt-status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-type.opt-index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game.opt-status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game.opt-index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game.opt-edit-do',
                    'method' => 'optEditDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-vendor.opt-index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-vendor.opt-status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-type.opt-index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-type.opt-status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-channel.opt-status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-channel.opt-index-do',
                    'method' => 'indexDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.finance-channel.opt-edit-do',
                    'method' => 'optEditDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.bank.add-do',
                    'method' => 'addDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.bank.edit-do',
                    'method' => 'edit',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.bank.index-do',
                    'method' => 'index',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.bank.del-do',
                    'method' => 'delDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.bank.status-do',
                    'method' => 'status',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.bank.opt-status-do',
                    'method' => 'status',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.bank.opt-index-do',
                    'method' => 'status',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'merchant-api.login',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 1,
                ],
                [
                    'route_name' => 'headquarters-api.merchant-admin-user.detail',
                    'method' => 'detail',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.game-vendor.status-do',
                    'method' => 'statusDo',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.activity.status-do',
                    'method' => 'status',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.activity.index-do',
                    'method' => 'index',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.switch',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.assign-games',
                    'method' => 'assignGames',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.assigned-games',
                    'method' => 'assignedGames',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.unassign-games',
                    'method' => 'unassignGames',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.domain-detail',
                    'method' => 'domainDetail',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.get-search-data-of-assign-game',
                    'method' => 'getSearchDataOfAssignGame',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.email.send',
                    'method' => 'send',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.assigned-game-cancel',
                    'method' => 'assignedGameCancel',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.headquarters-admin-user.create',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.headquarters-admin-user.update-admin-group',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.headquarters-admin-user.delete-admin',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.headquarters-admin-user.update-password',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.headquarters-admin-user.self-update-password',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.headquarters-admin-user.search-admin',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.do-add',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.setting.login-log-detail',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.domain-add',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
                [
                    'route_name' => 'headquarters-api.platform.edit',
                    'method' => '',
                    'menu_group_id' => 5,
                    'is_open' => 0,
                ],
            ],
        );
    }
}
