<?php

use App\Models\DeveloperUsage\Backend\SystemRoutesBackend;
use Illuminate\Database\Seeder;

/**
 * Class SystemRoutesBackendSeeder
 */
class SystemRoutesBackendSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        SystemRoutesBackend::insert(
            [
             [
              'route_name'    => 'headquarters-api.login',
              'method'        => 'login',
              'menu_group_id' => 39,
              'title'         => '登录',
              'is_open'       => 1,
             ],
             [
              'route_name'    => 'headquarters-api.logout',
              'method'        => 'logout',
              'menu_group_id' => 39,
              'title'         => '登出',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.get-all-menu',
              'method'        => 'getAllMenu',
              'menu_group_id' => 39,
              'title'         => '总后台所有菜单列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.current-admin-menu',
              'method'        => 'currentPartnerMenu',
              'menu_group_id' => 39,
              'title'         => '当前管理员拥有的菜单列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.all-require-infos',
              'method'        => '',
              'menu_group_id' => 39,
              'title'         => '添加编辑路由时获取的可用路由列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.add',
              'method'        => 'add',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-添加',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.delete',
              'method'        => 'delete',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-删除',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.edit',
              'method'        => 'edit',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-编辑',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.change-parent',
              'method'        => 'changeParent',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-修改上级',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.menu.display',
              'method'        => 'display',
              'menu_group_id' => 30,
              'title'         => '总后台菜单-是否显示',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.detail',
              'method'        => 'detail',
              'menu_group_id' => 5,
              'title'         => '管理员分组-列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.create',
              'method'        => 'create',
              'menu_group_id' => 5,
              'title'         => '管理员分组-添加',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.edit',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '管理员分组-编辑',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.delete-access-group',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '管理员分组-删除',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.backend-admin-group.specific-group-users',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '管理员分组-管理员列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.get-all-menu',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '代理后台菜单-列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.add',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '代理后台菜单-添加',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.edit',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '代理后台菜单-编辑',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.delete',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '代理后台菜单-删除',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.change-parent',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '代理后台菜单-修改上级',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-menu.display',
              'method'        => 'display',
              'menu_group_id' => 5,
              'title'         => '代理后台菜单-是否显示',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.create',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台管理员-添加',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.update-admin-group',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台管理员-修改所属组',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.delete-admin',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台管理员-删除',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.update-password',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台管理员-修改其他管理员密码',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.self-update-password',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台管理员-管理员自己修改密码',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.search-admin',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台管理员-搜索管理员',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin-user.switch-admin',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台管理员-禁用启用',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.detail',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '厅主列表-列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.do-add',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '厅主列表-添加',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.edit',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '厅主列表-站点管理',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.switch',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '厅主列表-禁用启用',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.domain-detail',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '厅主列表-域名管理-列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.domain-add',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '厅主列表-域名管理-添加',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.maintain',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '厅主列表-维护',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-route.index',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台路由-列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-route.do-add',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台路由-添加',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-route.edit',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台路由-编辑',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-route.delete',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '总后台路由-删除',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-route.index',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '代理后台路由-列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-route.do-add',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '代理后台路由-添加',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-route.edit',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '代理后台路由-编辑',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.merchant-route.delete',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '代理后台路由-删除',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.login-log.index',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '登录日志-列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.index',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '短信配置-列表',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.do-add',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '短信配置-添加',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.edit',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '短信配置-编辑',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.delete',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '短信配置-删除',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.sms-config.status',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '短信配置-禁用启用',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assign-games',
              'method'        => 'assignGames',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assigned-games',
              'method'        => 'assignedGames',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.unassign-games',
              'method'        => 'unassignGames',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.get-search-data-of-assign-game',
              'method'        => 'getSearchDataOfAssignGame',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assigned-game-cancel',
              'method'        => 'assignedGameCancel',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.add-do',
              'method'        => 'addDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.edit-do',
              'method'        => 'editDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.del-do',
              'method'        => 'delDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.add-do',
              'method'        => 'addDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.edit-do',
              'method'        => 'editDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.del-do',
              'method'        => 'delDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.add-do',
              'method'        => 'addDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.edit-do',
              'method'        => 'editDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.del-do',
              'method'        => 'delDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.headquarters-admin.get-all-users',
              'method'        => '',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.add-do',
              'method'        => 'addDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.edit-do',
              'method'        => 'editDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.del-do',
              'method'        => 'delDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.add-do',
              'method'        => 'addDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.edit-do',
              'method'        => 'editDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.del-do',
              'method'        => 'delDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.add-do',
              'method'        => 'addDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.edit-do',
              'method'        => 'editDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.del-do',
              'method'        => 'delDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.get-search-condition',
              'method'        => 'getSearchCondition',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.get-search-condition',
              'method'        => 'getSearchCondition',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.opt-status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.opt-index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.opt-status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-type.opt-index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.opt-status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.opt-index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game.opt-edit-do',
              'method'        => 'optEditDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.opt-index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-vendor.opt-status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.opt-index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-type.opt-status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.opt-status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.opt-index-do',
              'method'        => 'indexDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.finance-channel.opt-edit-do',
              'method'        => 'optEditDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.add-do',
              'method'        => 'addDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.edit-do',
              'method'        => 'edit',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.index-do',
              'method'        => 'index',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.del-do',
              'method'        => 'delDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.status-do',
              'method'        => 'status',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.opt-status-do',
              'method'        => 'status',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.bank.opt-index-do',
              'method'        => 'status',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.game-vendor.status-do',
              'method'        => 'statusDo',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.activity.status-do',
              'method'        => 'status',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.activity.index-do',
              'method'        => 'index',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.send',
              'method'        => 'send',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.send-index',
              'method'        => 'sendIndex',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.received-index',
              'method'        => 'receivedIndex',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assign-activities',
              'method'        => 'assignActivities',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assigned-activities',
              'method'        => 'assignedActivities',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.unassign-activities',
              'method'        => 'unassignActivities',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.platform.assigned-activity-cancel',
              'method'        => 'assignedActivityCancel',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.recent-contact',
              'method'        => 'recentContact',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.contact',
              'method'        => 'contact',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
             [
              'route_name'    => 'headquarters-api.email.read-email',
              'method'        => 'readEmail',
              'menu_group_id' => 5,
              'title'         => '',
              'is_open'       => 0,
             ],
            ],
        );
    }
}
