<?php

use App\Models\DeveloperUsage\Merchant\SystemRoutesMerchant;
use Illuminate\Database\Seeder;

/**
 * Class SystemRoutesMerchantSeeder
 */
class SystemRoutesMerchantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        SystemRoutesMerchant::insert(
            [
             [
              'route_name'    => 'merchant-api.frontend-user.index',
              'menu_group_id' => 4,
              'title'         => '会员管理-会员列表-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\FrontendUserController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.frontend-user.login-log',
              'menu_group_id' => 5,
              'title'         => '会员管理-登录记录-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\FrontendUserController',
              'method'        => 'loginLog',
             ],
             [
              'route_name'    => 'merchant-api.user-tags.index',
              'menu_group_id' => 6,
              'title'         => '会员管理-标签管理-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UsersTagController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.user-tags.do-add',
              'menu_group_id' => 6,
              'title'         => '会员管理-标签管理-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UsersTagController',
              'method'        => 'doAdd',
             ],
             [
              'route_name'    => 'merchant-api.user-tags.edit',
              'menu_group_id' => 6,
              'title'         => '会员管理-标签管理-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UsersTagController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.user-tags.delete',
              'menu_group_id' => 6,
              'title'         => '会员管理-标签管理-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UsersTagController',
              'method'        => 'delete',
             ],
             [
              'route_name'    => 'merchant-api.frontend-user-black-list.index',
              'menu_group_id' => 7,
              'title'         => '会员管理-黑名单管理-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UserBlackListController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.frontend-user-black-list.detail',
              'menu_group_id' => 7,
              'title'         => '会员管理-黑名单管理-详情',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UserBlackListController',
              'method'        => 'detail',
             ],
             [
              'route_name'    => 'merchant-api.frontend-user-black-list.remove',
              'menu_group_id' => 7,
              'title'         => '会员管理-黑名单管理-启用',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UserBlackListController',
              'method'        => 'remove',
             ],
             [
              'route_name'    => 'merchant-api.user-grade.config',
              'menu_group_id' => 8,
              'title'         => '会员管理-等级设置-晋级规则',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UserGradeController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.user-grade.index',
              'menu_group_id' => 8,
              'title'         => '会员管理-等级设置-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UserGradeController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.user-grade.do-add',
              'menu_group_id' => 8,
              'title'         => '会员管理-等级设置-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UserGradeController',
              'method'        => 'doAdd',
             ],
             [
              'route_name'    => 'merchant-api.user-grade.edit',
              'menu_group_id' => 8,
              'title'         => '会员管理-等级设置-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UserGradeController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.user-grade.delete',
              'menu_group_id' => 8,
              'title'         => '会员管理-等级设置-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\UserGradeController',
              'method'        => 'delete',
             ],
             [
              'route_name'    => 'merchant-api.commission.index',
              'menu_group_id' => 9,
              'title'         => '会员管理-洗码设置-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\CommissionController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.commission.do-add',
              'menu_group_id' => 9,
              'title'         => '会员管理-洗码设置-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\CommissionController',
              'method'        => 'doAdd',
             ],
             [
              'route_name'    => 'merchant-api.commission.edit',
              'menu_group_id' => 9,
              'title'         => '会员管理-洗码设置-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\CommissionController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.commission.delete',
              'menu_group_id' => 9,
              'title'         => '会员管理-洗码设置-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\User\CommissionController',
              'method'        => 'delete',
             ],
             [
              'route_name'    => 'merchant-api.recharge-order.index',
              'menu_group_id' => 11,
              'title'         => '财务管理-入款订单-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\RechargeOrderController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.recharge-order.get-finance-types',
              'menu_group_id' => 11,
              'title'         => '财务管理-入款订单-获取支付方式',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\RechargeOrderController',
              'method'        => 'getFinanceTypes',
             ],
             [
              'route_name'    => 'merchant-api.recharge-order.handle-success',
              'menu_group_id' => 11,
              'title'         => '财务管理-入款订单-手动入款',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\RechargeOrderController',
              'method'        => 'handleSuccess',
             ],
             [
              'route_name'    => 'merchant-api.recharge-order.check-pass',
              'menu_group_id' => 11,
              'title'         => '财务管理-入款订单-审核通过',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\RechargeOrderController',
              'method'        => 'checkPass',
             ],
             [
              'route_name'    => 'merchant-api.recharge-order.check-refuse',
              'menu_group_id' => 11,
              'title'         => '财务管理-入款订单-审核拒绝',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\RechargeOrderController',
              'method'        => 'checkRefuse',
             ],
             [
              'route_name'    => 'merchant-api.handle-save-buckle.handle-save',
              'menu_group_id' => 12,
              'title'         => '财务管理-人工存取-人工充值',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\HandleSaveBuckleRecordController',
              'method'        => 'handleSave',
             ],
             [
              'route_name'    => 'merchant-api.handle-save-buckle.save-index',
              'menu_group_id' => 12,
              'title'         => '财务管理-人工存取-人工充值列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\HandleSaveBuckleRecordController',
              'method'        => 'saveIndex',
             ],
             [
              'route_name'    => 'merchant-api.handle-save-buckle.handle-buckle',
              'menu_group_id' => 12,
              'title'         => '财务管理-人工存取-人工扣款',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\HandleSaveBuckleRecordController',
              'method'        => 'handleBuckle',
             ],
             [
              'route_name'    => 'merchant-api.handle-save-buckle.buckle-index',
              'menu_group_id' => 12,
              'title'         => '财务管理-人工存取-人工扣款列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\HandleSaveBuckleRecordController',
              'method'        => 'buckleIndex',
             ],
             [
              'route_name'    => 'merchant-api.withdraw-order.check-index',
              'menu_group_id' => 13,
              'title'         => '财务管理-出款审核-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\WithdrawOrderController',
              'method'        => 'checkIndex',
             ],
             [
              'route_name'    => 'merchant-api.withdraw-order.check-pass',
              'menu_group_id' => 13,
              'title'         => '财务管理-出款审核-审核通过',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\WithdrawOrderController',
              'method'        => 'checkPass',
             ],
             [
              'route_name'    => 'merchant-api.withdraw-order.check-refuse',
              'menu_group_id' => 13,
              'title'         => '财务管理-出款审核-审核拒绝',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\WithdrawOrderController',
              'method'        => 'checkRefuse',
             ],
             [
              'route_name'    => 'merchant-api.withdraw-order.out-index',
              'menu_group_id' => 14,
              'title'         => '财务管理-出款订单-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\WithdrawOrderController',
              'method'        => 'outIndex',
             ],
             [
              'route_name'    => 'merchant-api.withdraw-order.out-success',
              'menu_group_id' => 14,
              'title'         => '财务管理-出款订单-出款通过',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\WithdrawOrderController',
              'method'        => 'outSuccess',
             ],
             [
              'route_name'    => 'merchant-api.withdraw-order.out-refuse',
              'menu_group_id' => 14,
              'title'         => '财务管理-出款订单-出款拒绝',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\WithdrawOrderController',
              'method'        => 'outRefuse',
             ],
             [
              'route_name'    => 'merchant-api.marquee-notice.add-do',
              'menu_group_id' => 17,
              'title'         => '公告管理-跑马灯消息-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\MarqueeNoticeController',
              'method'        => 'addDo',
             ],
             [
              'route_name'    => 'merchant-api.marquee-notice.index',
              'menu_group_id' => 17,
              'title'         => '公告管理-跑马灯消息-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\MarqueeNoticeController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.marquee-notice.edit',
              'menu_group_id' => 17,
              'title'         => '公告管理-跑马灯消息-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\MarqueeNoticeController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.marquee-notice.del-do',
              'menu_group_id' => 17,
              'title'         => '公告管理-跑马灯消息-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\MarqueeNoticeController',
              'method'        => 'delDo',
             ],
             [
              'route_name'    => 'merchant-api.marquee-notice.status',
              'menu_group_id' => 17,
              'title'         => '公告管理-跑马灯消息-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\MarqueeNoticeController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.system-notice.add-do',
              'menu_group_id' => 18,
              'title'         => '公告管理-系统公告-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\SystemNoticeController',
              'method'        => 'addDo',
             ],
             [
              'route_name'    => 'merchant-api.system-notice.index',
              'menu_group_id' => 18,
              'title'         => '公告管理-系统公告-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\SystemNoticeController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.system-notice.edit',
              'menu_group_id' => 18,
              'title'         => '公告管理-系统公告-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\SystemNoticeController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.system-notice.del-do',
              'menu_group_id' => 18,
              'title'         => '公告管理-系统公告-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\SystemNoticeController',
              'method'        => 'delDo',
             ],
             [
              'route_name'    => 'merchant-api.system-notice.status',
              'menu_group_id' => 18,
              'title'         => '公告管理-系统公告-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\SystemNoticeController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.login-notice.add-do',
              'menu_group_id' => 19,
              'title'         => '公告管理-登录弹窗公告-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\LoginNoticeController',
              'method'        => 'addDo',
             ],
             [
              'route_name'    => 'merchant-api.login-notice.index',
              'menu_group_id' => 19,
              'title'         => '公告管理-登录弹窗公告-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\LoginNoticeController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.login-notice.edit',
              'menu_group_id' => 19,
              'title'         => '公告管理-登录弹窗公告-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\LoginNoticeController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.login-notice.del-do',
              'menu_group_id' => 19,
              'title'         => '公告管理-登录弹窗公告-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\LoginNoticeController',
              'method'        => 'delDo',
             ],
             [
              'route_name'    => 'merchant-api.login-notice.status',
              'menu_group_id' => 19,
              'title'         => '公告管理-登录弹窗公告-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\LoginNoticeController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.carousel-notice.add-do',
              'menu_group_id' => 20,
              'title'         => '公告管理-轮播公告-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\CarouselNoticeController',
              'method'        => 'addDo',
             ],
             [
              'route_name'    => 'merchant-api.carousel-notice.index',
              'menu_group_id' => 20,
              'title'         => '公告管理-轮播公告-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\CarouselNoticeController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.carousel-notice.edit',
              'menu_group_id' => 20,
              'title'         => '公告管理-轮播公告-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\CarouselNoticeController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.carousel-notice.del-do',
              'menu_group_id' => 20,
              'title'         => '公告管理-轮播公告-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\CarouselNoticeController',
              'method'        => 'delDo',
             ],
             [
              'route_name'    => 'merchant-api.carousel-notice.status',
              'menu_group_id' => 20,
              'title'         => '公告管理-轮播公告-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Notice\CarouselNoticeController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.email.send',
              'menu_group_id' => 22,
              'title'         => '邮件系统-发邮件-发送',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Email\SystemEmailController',
              'method'        => 'send',
             ],
             [
              'route_name'    => 'merchant-api.email.received-index',
              'menu_group_id' => 23,
              'title'         => '邮件系统-收件箱-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Email\SystemEmailController',
              'method'        => 'receivedIndex',
             ],
             [
              'route_name'    => 'merchant-api.email.read-email',
              'menu_group_id' => 23,
              'title'         => '邮件系统-收件箱-读邮件',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Email\SystemEmailController',
              'method'        => 'readEmail',
             ],
             [
              'route_name'    => 'merchant-api.email.send-index',
              'menu_group_id' => 24,
              'title'         => '邮件系统-已发邮件-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Email\SystemEmailController',
              'method'        => 'sendIndex',
             ],
             [
              'route_name'    => 'merchant-api.report.user-audit',
              'menu_group_id' => 34,
              'title'         => '报表管理-会员稽核-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Report\ReportController',
              'method'        => 'userAudit',
             ],
             [
              'route_name'    => 'merchant-api.game.upload',
              'menu_group_id' => 34,
              'title'         => '游戏管理-游戏-上传图片',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'upload',
             ],
             [
              'route_name'    => 'merchant-api.game.h5-index',
              'menu_group_id' => 35,
              'title'         => '游戏管理-H5游戏管理-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'h5Index',
             ],
             [
              'route_name'    => 'merchant-api.game.pc-index',
              'menu_group_id' => 36,
              'title'         => '游戏管理-PC游戏管理-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'pcIndex',
             ],
             [
              'route_name'    => 'merchant-api.game.app-index',
              'menu_group_id' => 37,
              'title'         => '游戏管理-APP游戏管理-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'appIndex',
             ],
             [
              'route_name'    => 'merchant-api.game.status',
              'menu_group_id' => 37,
              'title'         => '游戏管理-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.game.do-hot',
              'menu_group_id' => 37,
              'title'         => '游戏管理-更改热门属性',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'doHot',
             ],
             [
              'route_name'    => 'merchant-api.game.sort',
              'menu_group_id' => 37,
              'title'         => '游戏管理-排序',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'sort',
             ],
             [
              'route_name'    => 'merchant-api.game.maintain',
              'menu_group_id' => 37,
              'title'         => '游戏管理-维护',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'maintain',
             ],
             [
              'route_name'    => 'merchant-api.game.recommend',
              'menu_group_id' => 37,
              'title'         => '游戏管理-更改推荐属性',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'recommend',
             ],
             [
              'route_name'    => 'merchant-api.game.get-search-condition-data',
              'menu_group_id' => 37,
              'title'         => '游戏管理-搜索状态数据',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameController',
              'method'        => 'getSearchConditionData',
             ],
             [
              'route_name'    => 'merchant-api.game-vendor.index',
              'menu_group_id' => 38,
              'title'         => '游戏管理-平台管理-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameVendorController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.game-vendor.status',
              'menu_group_id' => 38,
              'title'         => '游戏管理-平台管理-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameVendorController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.game-vendor.sort',
              'menu_group_id' => 38,
              'title'         => '游戏管理-平台管理-排序',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameVendorController',
              'method'        => 'sort',
             ],
             [
              'route_name'    => 'merchant-api.game-vendor.upload',
              'menu_group_id' => 38,
              'title'         => '游戏管理-平台管理-上传图片',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameVendorController',
              'method'        => 'upload',
             ],
             [
              'route_name'    => 'merchant-api.game-type.index',
              'menu_group_id' => 39,
              'title'         => '游戏管理-分类管理-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameTypeController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.game-type.status',
              'menu_group_id' => 39,
              'title'         => '游戏管理-分类管理-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\GameTypeController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.activity-static.add-do',
              'menu_group_id' => 41,
              'title'         => '活动管理-静态活动-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Activity\ActivityStaticController',
              'method'        => 'addDo',
             ],
             [
              'route_name'    => 'merchant-api.activity-static.index',
              'menu_group_id' => 41,
              'title'         => '活动管理-静态活动-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Activity\ActivityStaticController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.activity-static.edit',
              'menu_group_id' => 41,
              'title'         => '活动管理-静态活动-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Activity\ActivityStaticController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.activity-static.del-do',
              'menu_group_id' => 41,
              'title'         => '活动管理-静态活动-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Activity\ActivityStaticController',
              'method'        => 'delDo',
             ],
             [
              'route_name'    => 'merchant-api.activity-static.status',
              'menu_group_id' => 41,
              'title'         => '活动管理-静态活动-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Activity\ActivityStaticController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.activity-dyn.index',
              'menu_group_id' => 42,
              'title'         => '活动管理-动态活动-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Activity\ActivityDynController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.activity-dyn.status',
              'menu_group_id' => 42,
              'title'         => '活动管理-动态活动-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Activity\ActivityDynController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.activity-dyn.save-pic',
              'menu_group_id' => 42,
              'title'         => '活动管理-动态活动-上传图片',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Activity\ActivityDynController',
              'method'        => 'savePic',
             ],
             [
              'route_name'    => 'merchant-api.offline-finance.add-do',
              'menu_group_id' => 44,
              'title'         => '金流管理-线下支付配置-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OfflineFinanceController',
              'method'        => 'addDo',
             ],
             [
              'route_name'    => 'merchant-api.offline-finance.index',
              'menu_group_id' => 44,
              'title'         => '金流管理-线下支付配置-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OfflineFinanceController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.offline-finance.edit',
              'menu_group_id' => 44,
              'title'         => '金流管理-线下支付配置-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OfflineFinanceController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.offline-finance.edit-get',
              'menu_group_id' => 44,
              'title'         => '金流管理-线下支付配置-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OfflineFinanceController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.offline-finance.del-do',
              'menu_group_id' => 44,
              'title'         => '金流管理-线下支付配置-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OfflineFinanceController',
              'method'        => 'delDo',
             ],
             [
              'route_name'    => 'merchant-api.offline-finance.status',
              'menu_group_id' => 44,
              'title'         => '金流管理-线下支付配置-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OfflineFinanceController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.offline-finance.types',
              'menu_group_id' => 44,
              'title'         => '金流管理-线下支付配置-分类列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OfflineFinanceController',
              'method'        => 'types',
             ],
             [
              'route_name'    => 'merchant-api.bank.get-system-banks',
              'menu_group_id' => 44,
              'title'         => '金流管理-线下支付配置-获取银行列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Bank\BankController',
              'method'        => 'getSystemBanks',
             ],
             [
              'route_name'    => 'merchant-api.online-finance.get-channels',
              'menu_group_id' => 45,
              'title'         => '金流管理-线上金流配置-获取金流通道',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OnlineFinanceController',
              'method'        => 'getChannels',
             ],
             [
              'route_name'    => 'merchant-api.online-finance.add-do',
              'menu_group_id' => 45,
              'title'         => '金流管理-线上金流配置-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OnlineFinanceController',
              'method'        => 'addDo',
             ],
             [
              'route_name'    => 'merchant-api.online-finance.index',
              'menu_group_id' => 45,
              'title'         => '金流管理-线上金流配置-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OnlineFinanceController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.online-finance.edit',
              'menu_group_id' => 45,
              'title'         => '金流管理-线上金流配置-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OnlineFinanceController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.online-finance.del-do',
              'menu_group_id' => 45,
              'title'         => '金流管理-线上金流配置-获取金流通道',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OnlineFinanceController',
              'method'        => 'delDo',
             ],
             [
              'route_name'    => 'merchant-api.online-finance.status',
              'menu_group_id' => 45,
              'title'         => '金流管理-线上金流配置-改变状态',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Finance\OnlineFinanceController',
              'method'        => 'status',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-group.detail',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminGroupController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-group.create',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminGroupController',
              'method'        => 'create',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-group.edit',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminGroupController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-group.delete',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminGroupController',
              'method'        => 'destroy',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-group.specific-group-users',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-管理员列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminGroupController',
              'method'        => 'specificGroupUsers',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-user.get-all-admins',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-所有管理员',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminUserController',
              'method'        => 'allAdmins',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-user.create',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminUserController',
              'method'        => 'create',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-user.update-admin-group',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-更换组',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminUserController',
              'method'        => 'updateAdminGroup',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-user.delete-admin',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminUserController',
              'method'        => 'deletePartnerAdmin',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-user.search-admin',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-搜索',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminUserController',
              'method'        => 'searchAdmin',
             ],
             [
              'route_name'    => 'merchant-api.merchant-admin-user.switch-admin',
              'menu_group_id' => 51,
              'title'         => '设置管理-管理员分组-禁用启用',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Admin\MerchantAdminUserController',
              'method'        => 'switchAdmin',
             ],
             [
              'route_name'    => 'merchant-api.config.index',
              'menu_group_id' => 52,
              'title'         => '设置管理-全域设置-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\ConfigController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.config.edit',
              'menu_group_id' => 52,
              'title'         => '设置管理-全域设置-修改设置',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\ConfigController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.costomer-service.index',
              'menu_group_id' => 53,
              'title'         => '设置管理-客服设置-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\CostomerServiceController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.costomer-service.do-add',
              'menu_group_id' => 53,
              'title'         => '设置管理-客服设置-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\CostomerServiceController',
              'method'        => 'doAdd',
             ],
             [
              'route_name'    => 'merchant-api.costomer-service.edit',
              'menu_group_id' => 53,
              'title'         => '设置管理-客服设置-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\CostomerServiceController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.costomer-service.delete',
              'menu_group_id' => 53,
              'title'         => '设置管理-客服设置-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\CostomerServiceController',
              'method'        => 'delete',
             ],
             [
              'route_name'    => 'merchant-api.help-center.index',
              'menu_group_id' => 54,
              'title'         => '设置管理-帮助设置-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\HelpCenterController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.help-center.do-add',
              'menu_group_id' => 54,
              'title'         => '设置管理-帮助设置-添加',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\HelpCenterController',
              'method'        => 'doAdd',
             ],
             [
              'route_name'    => 'merchant-api.help-center.edit',
              'menu_group_id' => 54,
              'title'         => '设置管理-帮助设置-编辑',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\HelpCenterController',
              'method'        => 'edit',
             ],
             [
              'route_name'    => 'merchant-api.help-center.delete',
              'menu_group_id' => 54,
              'title'         => '设置管理-帮助设置-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\HelpCenterController',
              'method'        => 'delete',
             ],
             [
              'route_name'    => 'merchant-api.bank-cards.index',
              'menu_group_id' => 56,
              'title'         => '设置管理-银行卡反查-列表',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\BankCardsController',
              'method'        => 'index',
             ],
             [
              'route_name'    => 'merchant-api.bank-cards.delete',
              'menu_group_id' => 56,
              'title'         => '设置管理-银行卡反查-删除',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\System\BankCardsController',
              'method'        => 'delete',
             ],
             [
              'route_name'    => 'merchant-api.login',
              'menu_group_id' => 58,
              'title'         => '登录',
              'is_open'       => 1,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\MerchantAuthController',
              'method'        => 'login',
             ],
             [
              'route_name'    => 'merchant-api.logout',
              'menu_group_id' => 58,
              'title'         => '登出',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\MerchantAuthController',
              'method'        => 'logout',
             ],
             [
              'route_name'    => 'merchant-api.menu.current-admin-menu',
              'menu_group_id' => 58,
              'title'         => '当前管理员拥有的菜单',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\MenuController',
              'method'        => 'currentAdminMenu',
             ],
             [
              'route_name'    => 'merchant-api.upload',
              'menu_group_id' => 58,
              'title'         => '上传图片',
              'is_open'       => 0,
              'controller'    => 'App\Http\Controllers\CommonApi\UploadController',
              'method'        => 'upload',
             ],
             [
              'route_name'    => 'merchant-api.game.ackOut',
              'menu_group_id' => 59,
              'title'         => '玩家追号，投注等接受回调地址',
              'is_open'       => 1,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\AcknowledgementController',
              'method'        => 'ackOut',
             ],
             [
              'route_name'    => 'merchant-api.game.ackIn',
              'menu_group_id' => 59,
              'title'         => '玩家撤单，余额退回平台接收地址',
              'is_open'       => 1,
              'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Game\AcknowledgementController',
              'method'        => 'ackIn',
             ],
             
             // [
             //  'route_name'    => 'merchant-api.bank.index',
             //  'menu_group_id' => 2,
             //  'title'         => '',
             //  'is_open'       => 0,
             //  'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Bank\BankController',
             //  'method'        => 'index',
             // ],
             // [
             //  'route_name'    => 'merchant-api.bank.status',
             //  'menu_group_id' => 2,
             //  'title'         => '',
             //  'is_open'       => 0,
             //  'controller'    => 'App\Http\Controllers\BackendApi\Merchant\Bank\BankController',
             //  'method'        => 'status',
             // ],
            ],
        );
    }
}
