<?php

use App\Models\DeveloperUsage\Frontend\SystemRoutesMobile;
use Illuminate\Database\Seeder;

/**
 * Class SystemRoutesMobileSeeder
 */
class SystemRoutesMobileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        SystemRoutesMobile::insert(
            [
             [
              'id'                => 1,
              'route_name'        => 'app-api.login',
              'controller'        => null,
              'method'            => 'login',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 1,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 2,
              'route_name'        => 'app-api.logout',
              'controller'        => null,
              'method'            => 'logout',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 3,
              'route_name'        => 'app-api.user.refresh-token',
              'controller'        => null,
              'method'            => 'refreshToken',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 4,
              'route_name'        => 'app-api.games-lobby.rich-list',
              'controller'        => null,
              'method'            => 'richList',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 1,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 5,
              'route_name'        => 'app-api.games-lobby.games-categories',
              'controller'        => null,
              'method'            => 'category',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 1,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 6,
              'route_name'        => 'app-api.user.information',
              'controller'        => null,
              'method'            => 'information',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 7,
              'route_name'        => 'app-api.user.game-list',
              'controller'        => null,
              'method'            => 'gameList',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 1,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 8,
              'route_name'        => 'app-api.register',
              'controller'        => null,
              'method'            => 'store',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 1,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 9,
              'route_name'        => 'app-api.register.verification-code',
              'controller'        => null,
              'method'            => 'code',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 1,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 10,
              'route_name'        => 'app-api.user.reset-password',
              'controller'        => null,
              'method'            => 'password',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 1,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 11,
              'route_name'        => 'app-api.reset-password.verification-code',
              'controller'        => null,
              'method'            => 'passwordCode',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 1,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 12,
              'route_name'        => 'app-api.system.avatar',
              'controller'        => null,
              'method'            => 'avatar',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 13,
              'route_name'        => 'app-api.account.list',
              'controller'        => null,
              'method'            => 'accountList',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 14,
              'route_name'        => 'app-api.system.banks',
              'controller'        => null,
              'method'            => 'banks',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 15,
              'route_name'        => 'app-api.account.bank-card.save',
              'controller'        => null,
              'method'            => 'bankCardSave',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 16,
              'route_name'        => 'app-api.account.alipay.save',
              'controller'        => null,
              'method'            => 'aliPaySave',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 17,
              'route_name'        => 'app-api.user.grades',
              'controller'        => null,
              'method'            => 'grades',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 18,
              'route_name'        => 'app-api.user.information',
              'controller'        => null,
              'method'            => 'updateInformation',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 19,
              'route_name'        => 'app-api.user.dynamic-information',
              'controller'        => null,
              'method'            => 'dynamicInformation',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 20,
              'route_name'        => 'app-api.account.destroy',
              'controller'        => null,
              'method'            => 'accountDestroy',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 21,
              'route_name'        => 'app-api.account.withdraw',
              'controller'        => null,
              'method'            => 'withdraw',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 22,
              'route_name'        => 'app-api.account.recentness',
              'controller'        => null,
              'method'            => 'recent',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 23,
              'route_name'        => 'app-api.account.records',
              'controller'        => null,
              'method'            => 'record',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 24,
              'route_name'        => 'app-api.account.promotion-gifts',
              'controller'        => null,
              'method'            => 'promotionGift',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 25,
              'route_name'        => 'app-api.account.weekly-gifts',
              'controller'        => null,
              'method'            => 'weeklyGift',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 26,
              'route_name'        => 'app-api.recharge.types',
              'controller'        => null,
              'method'            => 'types',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 27,
              'route_name'        => 'app-api.recharge.channels',
              'controller'        => null,
              'method'            => 'channels',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
             [
              'id'                => 28,
              'route_name'        => 'app-api.recharge.recharge',
              'controller'        => null,
              'method'            => 'recharge',
              'frontend_model_id' => null,
              'title'             => null,
              'description'       => null,
              'is_open'           => 0,
              'created_at'        => null,
              'updated_at'        => null,
             ],
            ],
        );
    }
}
